resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'
ui_page 'html/index.html'

files {
	'html/index.html',
	'html/static/css/app.css',
	'html/static/js/app.js',
	'html/static/js/manifest.js',
	'html/static/js/vendor.js',

	'html/static/config/config.json',
	
	-- Coque
	'html/static/img/coque/blue.png',
	'html/static/img/coque/s8.png',
	'html/static/img/coque/red.png',
	'html/static/img/coque/grey.png',
	'html/static/img/coque/pink.png',
	'html/static/img/coque/no_cover.png',


	
	-- Background
	'html/static/img/background/back001.jpg',
	'html/static/img/background/back002.jpg',
	'html/static/img/background/back003.jpg',
	'html/static/img/background/color.jpg',
	'html/static/img/background/humo.jpg',
	'html/static/img/background/iluminacion.jpg',
	'html/static/img/background/neon.jpg',
	'html/static/img/background/oscuridad.jpg',
	'html/static/img/background/paisajes.jpg',
	'html/static/img/background/playa.jpg',
	'html/static/img/background/tokio.jpg',
	'html/static/img/background/Emilia.jpg',
	'html/static/img/background/FORTNITE.jpg',
	'html/static/img/background/R6.jpg',
	'html/static/img/background/sao.jpg',
	'html/static/img/background/Tohka&Yoshinon.jpg',
	'html/static/img/background/Flash.jpg',

	'html/static/img/background/01.jpg',
	'html/static/img/background/02.jpg',
	'html/static/img/background/03.jpg',
	'html/static/img/background/04.jpg',
	'html/static/img/background/05.jpg',
	'html/static/img/background/06.jpg',
	'html/static/img/background/07.jpg',
	'html/static/img/background/08.jpg',
	'html/static/img/background/09.jpg',
	'html/static/img/background/10.jpg',
	'html/static/img/background/11.jpg',
	'html/static/img/background/12.jpg',
	'html/static/img/background/13.jpg',
	'html/static/img/background/14.jpg',
	'html/static/img/background/15.jpg',
	'html/static/img/background/16.jpg',
	'html/static/img/background/17.jpg',
	'html/static/img/background/18.jpg',
	'html/static/img/background/19.jpg',
	'html/static/img/background/20.jpg',
	'html/static/img/background/21.jpg',
	'html/static/img/background/back013.jpg',
	'html/static/img/background/back014.jpg',
	'html/static/img/background/back016.jpg',
	'html/static/img/background/back017.jpg',
	'html/static/img/background/back015.jpg',
	'html/static/img/background/original.gif',
	'html/static/img/background/back001.jpg',
	'html/static/img/background/back002.jpg',
	'html/static/img/background/back003.jpg',
	'html/static/img/background/back004.jpg',
	'html/static/img/background/back005.jpg',
	'html/static/img/background/back006.jpg',
	'html/static/img/background/back007.jpg',
	'html/static/img/background/back008.gif',
	'html/static/img/background/back009.gif',
	
	'html/static/img/icons_app/call.png',
	'html/static/img/icons_app/contacts.png',
	'html/static/img/icons_app/ff.png',
	'html/static/img/icons_app/itunes.svg',
	'html/static/img/icons_app/lsfd.png',
	'html/static/img/icons_app/sms.png',
	'html/static/img/icons_app/settings.png',
	'html/static/img/icons_app/menu.png',
	'html/static/img/icons_app/bourse.png',
	'html/static/img/icons_app/tchat.png',
	'html/static/img/icons_app/photo.png',
	'html/static/img/icons_app/policier.png',
	'html/static/img/icons_app/reddit.png',
	'html/static/img/icons_app/notes.png',
	'html/static/img/icons_app/bank.png',
	'html/static/img/icons_app/wifi.png',
	'html/static/img/icons_app/9gag.png',
	'html/static/img/icons_app/twitter.png',
	'html/static/img/icons_app/borrado.png',
	'html/static/img/icons_app/concess.png',
	'html/static/img/icons_app/ambulancier.png',
	'html/static/img/icons_app/boucherie.png',
	'html/static/img/icons_app/michekebab.png',
	'html/static/img/icons_app/barbe.png',
	'html/static/img/icons_app/gruppe6.png',
	'html/static/img/icons_app/crucial.png',
	'html/static/img/incon_app/bcso.png',
	'html/static/img/icons_app/fournisseur.png',
	'html/static/img/icons_app/tequilala.png',
	'html/static/img/icons_app/fbi.png',
	'html/static/img/icons_app/mecano.png',
	'html/static/img/icons_app/weazel.png',
	'html/static/img/icons_app/agent.png',
	'html/static/img/icons_app/unicorn.png',
	'html/static/img/icons_app/avocat.png',
	'html/static/img/icons_app/taxi.png',
	'html/static/img/icons_app/moto.png',
	'html/static/img/icons_app/mosley.png',
	'html/static/img/app_bank/fleeca_tar.png',
	'html/static/img/app_bank/tarjetas.png',

	'html/static/img/app_tchat/reddit.png',

	'html/static/img/twitter/bird.png',
	'html/static/img/twitter/default_profile.png',
	'html/static/sound/Twitter_Sound_Effect.ogg',

	'html/static/img/courbure.png',
	'html/static/fonts/fontawesome-webfont.eot',
	'html/static/fonts/fontawesome-webfont.ttf',
	'html/static/fonts/fontawesome-webfont.woff',
	'html/static/fonts/fontawesome-webfont.woff2',

	'html/static/sound/ring.ogg',
	'html/static/sound/ring2.ogg',
	'html/static/sound/bella_ciao.ogg',
	'html/static/sound/casa_papel.ogg',
	'html/static/sound/iphone_11.ogg',
	'html/static/sound/safaera.ogg',
	'html/static/sound/tusa.ogg',
	'html/static/sound/xtentacion.ogg',
	'html/static/sound/tchatNotification.ogg',
	'html/static/sound/Phone_Call_Sound_Effect.ogg',

}

client_script {
	"NativeUI.lua",
	"config.lua",
	"client/animation.lua",
	"client/client.lua",

	"client/photo.lua",
	"client/app_tchat.lua",
	"client/bank.lua",
	"client/twitter.lua"
}

server_script {
	'@mysql-async/lib/MySQL.lua',
	"config.lua",
	"server/server.lua",

	"server/app_tchat.lua",
	"server/twitter.lua"
}
