Config = {
    USE_ESSENTIALMODE_ADMIN_SYSTEM = true,
    -- only if USE_ESSENTIALMODE_ADMIN_SYSTEM is set to false
    ADMINS = {"steam:11000011b52d192"},
    CONTROL_TO_OPEN_PANEL = 38,
    CONTROL_TO_ADD_POINT = 182,
    CONTROL_TO_REMOVE_LAST_POINT = 311,
}