ESX = nil

TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

ESX.RegisterUsableItem('bread', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('bread', 1)

	TriggerClientEvent('esx_status:add', source, 'hunger', 200000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	xPlayer.showNotification("Vous avez mangé du pain")
end)
ESX.RegisterUsableItem('water', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('water', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 200000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	xPlayer.showNotification("Vous avez bu de l'eau")
end)
ESX.RegisterUsableItem('bigmac', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('bigmac', 1)

	TriggerClientEvent('esx_status:add', source, 'hunger', 500000)
	TriggerClientEvent('esx_basicneeds:bigmac', source)
	xPlayer.showNotification("Vous avez mangé un bigmac")
end)
ESX.RegisterUsableItem('frite', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('frite', 1)
	
	TriggerClientEvent('esx_status:add', source, 'thirst', -50000)
	TriggerClientEvent('esx_status:add', source, 'hunger', 160000)
	TriggerClientEvent('esx_basicneeds:onEatChips', source)
	xPlayer.showNotification("Vous avez mangé des frites")
end)
ESX.RegisterUsableItem('icetea', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('icetea', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 300000)
	TriggerClientEvent('esx_basicneeds:water', source)
	xPlayer.showNotification("Vous avez bu de l'ice tea")
end)
ESX.RegisterUsableItem('jusfruit', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('jusfruit', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 500000)
	TriggerClientEvent('esx_basicneeds:water', source)
	xPlayer.showNotification("Vous avez bu du jus de fruit")
end)
ESX.RegisterUsableItem('energy', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('energy', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 800000)
	TriggerClientEvent('esx_basicneeds:water', source)
	xPlayer.showNotification("Vous avez bu un energy")
end)
ESX.RegisterUsableItem('limonade', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('limonade', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 600000)
	TriggerClientEvent('esx_basicneeds:water', source)
	xPlayer.showNotification("Vous avez bu de la limonade")
end)
ESX.RegisterUsableItem('grapperaisin', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('grapperaisin', 1)

	TriggerClientEvent('esx_status:add', source, 'drunk', 50000)
	TriggerClientEvent('esx_status:add', source, 'thirst', 200000)
	TriggerClientEvent('esx_status:add', source, 'hunger', 700000)
	TriggerClientEvent('esx_basicneeds:water', source)
	xPlayer.showNotification("Vous avez mangé une grappe de raisin")
end)
ESX.RegisterUsableItem('orange', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('orange', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 60000)
	TriggerClientEvent('esx_status:add', source, 'hunger', 40000)
	TriggerClientEvent('esx_status:add', source, 'drunk', -60000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	xPlayer.showNotification("Vous avez mangé une orange")
end)
ESX.RegisterUsableItem('donuts', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('donuts', 1)

	TriggerClientEvent('esx_status:add', source, 'hunger', 80000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	xPlayer.showNotification("Vous avez mangé un donuts")
end)
ESX.RegisterUsableItem('sprite', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('sprite', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 60000)
	TriggerClientEvent('esx_basicneeds:water', source)
	xPlayer.showNotification("Vous avez bu du sprite")
end)
ESX.RegisterUsableItem('orange_pooch', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('orange_pooch', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 70000)
	TriggerClientEvent('esx_status:add', source, 'hunger', 60000)
	TriggerClientEvent('esx_status:add', source, 'drunk', -100000)
	TriggerClientEvent('esx_basicneeds:jusorange', source)
	xPlayer.showNotification("Vous avez bu du jus d'orange")
end)
ESX.RegisterUsableItem('pomme', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('pomme', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 40000)
	TriggerClientEvent('esx_status:add', source, 'hunger', 60000)
	TriggerClientEvent('esx_status:add', source, 'drunk', -60000)
	TriggerClientEvent('esx_status:add', source,'force', 20000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	xPlayer.showNotification("Vous avez mangé une pomme")
end)
ESX.RegisterUsableItem('pomme_pooch', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('pomme_pooch', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 80000)
	TriggerClientEvent('esx_status:add', source, 'hunger', 50000)
	TriggerClientEvent('esx_status:add', source, 'drunk', -100000)
	TriggerClientEvent('esx_status:remove', source, 'pee', 100000)
	TriggerClientEvent('esx_basicneeds:onDrink', source)
	xPlayer.showNotification("Vous avez bu du jus de pomme")
end)
ESX.RegisterUsableItem('chocolate', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('chocolate', 1)

	TriggerClientEvent('esx_status:add', source, 'hunger', 90000)
	TriggerClientEvent('esx_status:add', source, 'thirst', -40000)
	TriggerClientEvent('esx_status:add', source, 'drunk', -80000)
	TriggerClientEvent('esx_basicneeds:onEatChocolate', source)
	xPlayer.showNotification("Vous avez mangé du chocolat")
end)
ESX.RegisterUsableItem('donut', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('donut', 1)

	TriggerClientEvent('esx_status:add', source, 'hunger', 90000)
	TriggerClientEvent('esx_status:add', source, 'thirst', -40000)
	TriggerClientEvent('esx_basicneeds:onEatdonut', source)
	xPlayer.showNotification("Vous avez mangé un donut")
end)
ESX.RegisterUsableItem('drpepper', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('drpepper', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 160000)
	TriggerClientEvent('esx_status:add', source, 'hunger', -20000)
	TriggerClientEvent('esx_status:add', source, 'stress', 6000)
	TriggerClientEvent('esx_status:remove', source, 'pee', 100000)
	TriggerClientEvent('esx_basicneeds:onDrinkDrPepper', source)
	xPlayer.showNotification("Vous avez bu un dr pepper")
end)
ESX.RegisterUsableItem('cocktail', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('cocktail', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 140000)
	TriggerClientEvent('esx_status:add', source, 'hunger', 40000)
	TriggerClientEvent('esx_status:add', source,'force', 20000)
	TriggerClientEvent('esx_basicneeds:cocktail', source)
	xPlayer.showNotification("Vous avez bu un cocktail")
end)
ESX.RegisterUsableItem('soda', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('soda', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 140000)
	TriggerClientEvent('esx_status:add', source, 'hunger', -40000)
	TriggerClientEvent('esx_basicneeds:soda', source)
	xPlayer.showNotification("Vous avez bu une boisson")
end)
ESX.RegisterUsableItem('coca', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('coca', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 140000)
	TriggerClientEvent('esx_basicneeds:onDrinkCocaCola', source)
	xPlayer.showNotification("Vous avez bu un Coca Cola")
end)
ESX.RegisterUsableItem('sagres', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('sagres', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 140000)
	TriggerClientEvent('esx_status:add', source, 'drunk', 300000)
	TriggerClientEvent('esx_basicneeds:onDrinkBeer', source)
	xPlayer.showNotification("Vous avez bu une sagres")
end)
ESX.RegisterUsableItem('superbock', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('superbock', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 140000)
	TriggerClientEvent('esx_status:add', source, 'drunk', 300000)
	TriggerClientEvent('esx_basicneeds:onDrinkBeer', source)
	xPlayer.showNotification("Vous avez bu une superbock")
end)
ESX.RegisterUsableItem('sumol', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('sumol', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', 140000)
	TriggerClientEvent('esx_status:add', source, 'hunger', -40000)
	TriggerClientEvent('esx_basicneeds:soda', source)
	xPlayer.showNotification("Vous avez bu du sumol")
end)
ESX.RegisterUsableItem('viande', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('viande', 1)

	TriggerClientEvent('esx_status:add', source, 'thirst', -60000)
	TriggerClientEvent('esx_status:add', source, 'hunger', 100000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	xPlayer.showNotification("Vous avez mangé de la viande")
end)
ESX.RegisterUsableItem('raisin', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('raisin', 1)

	TriggerClientEvent('esx_status:add', source, 'hunger', 50000)
	TriggerClientEvent('esx_status:add', source, 'thirst', 50000)
	TriggerClientEvent('esx_status:add', source, 'drunk', -60000)
	TriggerClientEvent('esx_status:add', source,'force', 10000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	xPlayer.showNotification("Vous avez mangé du raisin")
end)
ESX.RegisterUsableItem('metreshooter', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('metreshooter', 1)

	TriggerClientEvent('esx_status:add', source, 'drunk', 1000000)
	TriggerClientEvent('esx_status:add', source,'force', 20000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	xPlayer.showNotification("Vous avez bu un metre de shooter")
end)
ESX.RegisterUsableItem('saucisson', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('saucisson', 1)

	TriggerClientEvent('esx_status:add', source, 'hunger', 100000)
    TriggerClientEvent('esx_status:add', source, 'thirst', -60000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	xPlayer.showNotification("Vous avez mangé du saucisson")
end)
ESX.RegisterUsableItem('bolchips', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('bolchips', 1)

	TriggerClientEvent('esx_status:add', source, 'hunger', 100000)
    TriggerClientEvent('esx_status:add', source, 'thirst', -60000)
	TriggerClientEvent('esx_basicneeds:onEatChips', source)
	xPlayer.showNotification("Vous avez mangé un bol de chips")

end)
ESX.RegisterUsableItem('bolpistache', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('bolpistache', 1)

	TriggerClientEvent('esx_status:add', source, 'hunger', 100000)
    TriggerClientEvent('esx_status:add', source, 'thirst', -60000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	xPlayer.showNotification("Vous avez mangé un bol de pistache")

end)
ESX.RegisterUsableItem('bolnoixcajou', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('bolnoixcajou', 1)

	TriggerClientEvent('esx_status:add', source, 'hunger', 110000)
	TriggerClientEvent('esx_status:add', source, 'thirst', -60000)
	TriggerClientEvent('esx_status:add', source, 'drunk', -60000)
	TriggerClientEvent('esx_status:add', source,'force', 20000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	xPlayer.showNotification("Vous avez mangé un bol de noix de cajou")
end)
ESX.RegisterUsableItem('bolcacahuetes', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('bolcacahuetes', 1)

	TriggerClientEvent('esx_status:add', source, 'hunger', 100000)
	TriggerClientEvent('esx_status:add', source, 'thirst', -60000)
	TriggerClientEvent('esx_status:add', source, 'drunk', -60000)
	TriggerClientEvent('esx_basicneeds:onEat', source)
	xPlayer.showNotification("Vous avez mangé un bol de cacahuetes")
end)
ESX.RegisterUsableItem('mkebab', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('mkebab', 1)
	
	TriggerClientEvent('esx_status:add', source, 'hunger', 400000)
	TriggerClientEvent('esx_status:add', source, 'thirst', -80000)
	TriggerClientEvent('esx_status:add', source, 'drunk', -100000)
	TriggerClientEvent('esx_status:add', source,'force', 20000)
	TriggerClientEvent('esx_basicneeds:onEatSandwich', source)
	xPlayer.showNotification("Vous avez mangé un maxi kebab")
end)
ESX.RegisterUsableItem('mtacos', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('mtacos', 1)
	
	TriggerClientEvent('esx_status:add', source, 'hunger', 380000)
	TriggerClientEvent('esx_basicneeds:onEatSandwich', source)
	xPlayer.showNotification("Vous avez mangé un maxi tacos")
end)
---
ESX.RegisterUsableItem('nachos', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('nachos', 1)
	
	TriggerClientEvent('esx_status:add', source, 'hunger', 3800000)
	TriggerClientEvent('esx_basicneeds:onEatSandwich', source)
	xPlayer.showNotification("Vous avez mangé un poulet roti")
end)
ESX.RegisterUsableItem('taco', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('taco', 1)
	
	TriggerClientEvent('esx_status:add', source, 'hunger', 3800000)
	TriggerClientEvent('esx_basicneeds:onEatSandwich', source)
	xPlayer.showNotification("Vous avez mangé un poulet au curri")
end)
ESX.RegisterUsableItem('buritto', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('buritto', 1)
	
	TriggerClientEvent('esx_status:add', source, 'hunger', 3800000)
	TriggerClientEvent('esx_basicneeds:onEatSandwich', source)
	xPlayer.showNotification("Vous avez mangé du boeuf roti")
end)
ESX.RegisterUsableItem('sandwich', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('sandwich', 1)
	
	TriggerClientEvent('esx_status:add', source, 'hunger', 380000)
	TriggerClientEvent('esx_basicneeds:onEatSandwich', source)
	xPlayer.showNotification("Vous avez mangé un sandwich")
end)
ESX.RegisterUsableItem('salade', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('salade', 1)
	
	TriggerClientEvent('esx_status:add', source, 'hunger', 380000)
	TriggerClientEvent('esx_status:add', source, 'thirst', -60000)
	TriggerClientEvent('esx_status:add', source, 'drunk', -100000)
	TriggerClientEvent('esx_basicneeds:onEatSandwich', source)
	xPlayer.showNotification("Vous avez mangé une salade mexicaine")
end)
ESX.RegisterUsableItem('coffe', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('coffe', 1)
	
	TriggerClientEvent('esx_status:add', source, 'thirst', 60000)
	TriggerClientEvent('esx_basicneeds:onDrinkCoffe', source)
	xPlayer.showNotification("Vous avez bu un café")
end)
ESX.RegisterUsableItem('champagne', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('champagne', 1)
	
	TriggerClientEvent('esx_status:add', source, 'thirst', 60000)
	TriggerClientEvent('esx_status:add', source, 'drunk', 100000)
	TriggerClientEvent('esx_basicneeds:onDrinkChampagne', source)
	xPlayer.showNotification("Vous avez bu du champagne")
end)
ESX.RegisterUsableItem('tea', function(source)
	local xPlayer  = ESX.GetPlayerFromId(source)
	xPlayer.removeInventoryItem('tea', 1)
	
	TriggerClientEvent('esx_status:add', source, 'thirst', 60000)
	TriggerClientEvent('esx_basicneeds:onDrinkCoffe', source)
	xPlayer.showNotification("Vous avez bu du thé")
end)

ESX.RegisterCommand('heal', 'superadmin', function(xPlayer, args, showError)
	args.playerId.triggerEvent('esx_basicneeds:healPlayer')
	args.playerId.triggerEvent('chat:addMessage', {args = {'^5HEAL', 'You have been healed.'}})
end, true, {help = 'Heal a player, or yourself - restores thirst, hunger and health.', validate = true, arguments = {
	{name = 'playerId', help = 'the player id', type = 'player'}
}})
