Config = {}


Config.Anims =  {
    ["S\'asseoir"] = {
        {name = "Jspske C1", anim = {"missheistdockssetup1ig_12@base", "talk_gantry_idle_base_worker2"}, func = 1},
        {name = "Jspske C2", anim = {"missheistdockssetup1ig_12@base", "talk_gantry_idle_base_worker4"}, func = 1},
        -- {name = "Sit 01", anim = {"amb@code_human_in_bus_passenger_idles@female@sit@base", "base"}, func = 1, a = -180.0},
        {name = "Par Terre", anim = {"anim@heists@fleeca_bank@ig_7_jetski_owner", "owner_idle"}, func = 1},
        {name = "Contre un mur", anim = "WORLD_HUMAN_LEANING"},
        {name = "Sur le Sol", anim = "WORLD_HUMAN_PICNIC"},
        -- {name = "Sit down", anim = {"anim@amb@office@seating@male@var_d@base@", "base"}, func = 1, a = -180.0},
        {name = "Cool", anim = {"anim@heists@heist_safehouse_intro@phone_couch@male", "phone_couch_male_idle"}, func = 1, a = -180.0},
        -- {name = "Sitting reflective", anim = {"missdrfriedlanderdrf_idles", "hands2face_michael"}, func = 1, a = -180.0},
        -- {name = "Sit down", anim = {"missdrfriedlanderdrf_idles", "hand2chin_michael"}, func = 1, a = -180.0},
        {name = "Meditation", anim = {"rcmcollect_paperleadinout@", "meditiate_idle"}, func = 1},
        {name = "Genoux sur le sol", anim = {"amb@medic@standing@kneel@base", "base"}, func = 1},
        -- {name = "Sit still", anim = {"missdrfriedlanderdrf_idles", "drf_idle_drf"}, func = 1},
        {name = "Chill", anim = {"missheistpaletoscoresetupleadin", "rbhs_mcs_1_leadin"}, func = 1, a = -180.0},
        {name = "Posey", anim = {"missfam2leadinoutmcs3", "onboat_leadin_pornguy_a"}, func = 1, a = -180.0},
        },
        ["Actions"] = {
        {name = "Glisser", anim = {"anim@arena@celeb@flat@solo@no_props@", "slide_a_player_a"}},
        {name = "Reverence", anim = {"anim@arena@celeb@podium@no_prop@", "regal_c_1st"}},
        {name = "Pleurer sur les genoux", anim = {"mp_bank_heist_1", "f_cower_01"}, func = 1},
        {name = "Jeter votre carnet", anim = "CODE_HUMAN_MEDIC_TIME_OF_DEATH"},
        {name = "Notes", anim = "WORLD_HUMAN_CLIPBOARD"},
        {name = "Siffler", anim = {"rcmnigel1c", "hailing_whistle_waive_a"}, func = 48},
        {name = "Faire des pompes", anim = "WORLD_HUMAN_PUSH_UPS"},
        {name = "Se sentir mal", anim = {"missfam5_blackout", "pass_out"}},
        {name = "Locoooo", anim = {"anim@mp_player_intcelebrationmale@you_loco", "you_loco"}},
        {name = "Trique", anim = {"anim@mp_player_intcelebrationmale@wank", "wank"}},
        {name = "Laché moi", anim = {"anim@mp_player_intcelebrationmale@freakout", "freakout"}},
        {name = "Mendier", anim = "WORLD_HUMAN_BUM_FREEWAY"},
        {name = "Applaudir", anim = "WORLD_HUMAN_CHEERING"},
        {name = "Auplaudir lentement", anim = {"anim@mp_player_intcelebrationmale@slow_clap", "slow_clap"}},
        {name = "Appel", anim = {"cellphone@", "cellphone_call_listen_base"}, func = 49},
        {name = "Encouragement", anim = {"mini@triathlon", "male_one_handed_a"}},
        {name = "Prendre une phoo", anim = "WORLD_HUMAN_MOBILE_FILM_SHOCKING"},
        {name = "Bras tendu", anim = {"nm@hands", "flail"}, func = 1},
        {name = "Yoga", anim = {"amb@world_human_yoga@male@base", "base_a"}},
        {name = "Same", anim = {"special_ped@mime@monologue_5@monologue_5a", "10_ig_1_wa_0"}},
        {name = "Faire des abdos", anim = "WORLD_HUMAN_SIT_UPS"},
        {name = "Jeter votre carte", anim = "WORLD_HUMAN_TOURIST_MAP"},
        {name = "Acrobatie 1", anim = {"anim@arena@celeb@flat@solo@no_props@", "cap_a_player_a"}},
        {name = "Acrobatie 2", anim = {"anim@arena@celeb@flat@solo@no_props@", "flip_a_player_a"}},
        {name = "Acrobatie 3", anim = {"anim@arena@celeb@flat@solo@no_props@", "pageant_a_player_a"}},
        {name = "Radio", anim = {"random@arrests", "generic_radio_chatter"}, func = 49},
        {name = "Jardiner", anim = {"amb@world_human_gardener_plant@male@base", "base"}},
        },
    ["Gestes"] = {
        {name = "Embrasser ses doigts", anim = {"anim@mp_player_intcelebrationfemale@finger_kiss", "finger_kiss"}},
        {name = "Quoi?", anim = {"gestures@f@standing@casual", "gesture_bring_it_on"}, func = 48},
        {name = "Casser", anim = {"gestures@f@standing@casual", "gesture_bye_hard"}, func = 48},
        {name = "Wesh", anim = {"gestures@f@standing@casual", "gesture_bye_soft"}, func = 48},
        {name = "Viens voir", anim = {"gestures@f@standing@casual", "gesture_come_here_hard"}, func = 48},
        {name = "Allez ..", anim = {"gestures@f@standing@casual", "gesture_come_here_soft"}, func = 48},
        {name = "WTF?", anim = {"gestures@f@standing@casual", "gesture_damn"}, func = 48},
        {name = "Tsss", anim = {"gestures@f@standing@casual", "gesture_displeased"}, func = 48},
        {name = "Calme toi", anim = {"gestures@f@standing@casual", "gesture_easy_now"}, func = 48},
        {name = "Ici", anim = {"gestures@f@standing@casual", "gesture_hand_down"}, func = 48},
        {name = "Gauche", anim = {"gestures@f@standing@casual", "gesture_hand_left"}, func = 48},
        {name = "Droite", anim = {"gestures@f@standing@casual", "gesture_hand_right"}, func = 48},
        {name = "Oh non", anim = {"gestures@f@standing@casual", "gesture_head_no"}, func = 48},
        {name = "Hey toi", anim = {"gestures@f@standing@casual", "gesture_hello"}, func = 48},
        {name = "Lourd", anim = {"gestures@f@standing@casual", "gesture_i_will"}, func = 48},
        {name = "Moi?", anim = {"gestures@f@standing@casual", "gesture_me_hard"}, func = 48},
        {name = "Moi", anim = {"gestures@f@standing@casual", "gesture_me"}, func = 48},
        {name = "Wesh2", anim = {"gestures@f@standing@casual", "gesture_no_way"}, func = 48},
        {name = "Non non", anim = {"gestures@f@standing@casual", "gesture_nod_no_hard"}, func = 48},
        {name = "Non", anim = {"gestures@f@standing@casual", "gesture_nod_no_soft"}, func = 48},
        {name = "Oui bresson", anim = {"gestures@f@standing@casual", "gesture_nod_yes_hard"}, func = 48},
        {name = "M\'ouais", anim = {"gestures@f@standing@casual", "gesture_nod_yes_soft"}, func = 48},
        {name = "C\'est ça", anim = {"gestures@f@standing@casual", "gesture_pleased"}, func = 48},
        {name = "Mon bro", anim = {"gestures@f@standing@casual", "gesture_point"}, func = 48},
        {name = "Aucune idée", anim = {"gestures@f@standing@casual", "gesture_shrug_hard"}, func = 48},
        {name = "Aucune ptn d\'idée'", anim = {"gestures@f@standing@casual", "gesture_shrug_soft"}, func = 48},
        {name = "Quoi ?!", anim = {"gestures@f@standing@casual", "gesture_what_hard"}, func = 48},
        {name = "Quoi normal ?!", anim = {"gestures@f@standing@casual", "gesture_what_soft"}, func = 48},
        -- {name = "Why", anim = {"gestures@f@standing@casual", "gesture_why_left"}, func = 48},
        -- {name = "", anim = {"gestures@f@standing@casual", "gesture_why"}, func = 48},
        {name = "Toi", anim = {"gestures@f@standing@casual", "gesture_you_hard"}, func = 48},
        {name = "Toi basique", anim = {"gestures@f@standing@casual", "gesture_you_soft"}, func = 48},
        {name = "C\'est le mien'", anim = {"gestures@f@standing@casual", "getsure_its_mine"}, func = 48},
        },
    ["Expressions"] = {
        {name = "Pouces", anim = {"anim@arena@celeb@flat@solo@no_props@", "thumbs_down_a_player_a"}, func = 48},
        {name = "Mort de rire", anim = {"anim@arena@celeb@flat@solo@no_props@", "taunt_d_player_b"}},
        {name = "Mauvais mood 1", anim = {"amb@world_human_stupor@male@base", "base"}, func = 1},
        {name = "Mauvais mood 2", anim = {"amb@world_human_stupor@male_looking_left@base", "base"}, func = 1},
        {name = "Bisoux", anim = {"mp_ped_interaction", "kisses_guy_a"}},
        {name = "Stressé", anim = {"rcmme_tracey1", "nervous_loop"}, func = 1},
        {name = "Paix", anim = {"anim@mp_player_intcelebrationmale@peace", "peace"}, func = 48},
        {name = "Clown trizo", anim = {"move_clown@p_m_two_idles@", "fidget_short_dance"}},
        {name = "Face Palm", anim = {"anim@mp_player_intcelebrationmale@face_palm", "face_palm"}},
        {name = "Patient", anim = {"special_ped@impotent_rage@base", "base"}, func = 1},
        {name = "Respect", anim = {"mp_player_int_upperbro_love", "mp_player_int_bro_love_fp"}, func = 48},
        {name = "Lunettes", anim = {"clothingspecs", "try_glasses_positive_a"}, func = 48},
        {name = "Reflexion", anim = {"misscarsteal4@aliens", "rehearsal_base_idle_director"}, func = 49},
        {name = "Regarde mon style", anim = {"clothingshirt", "try_shirt_positive_d"}, func = 48},
        {name = "Victoire", anim = {"mini@tennisexit@", "tennis_outro_win_01_female"}},
        {name = "LPF", anim = {"rcmbarry", "base"}},
        {name = "Ta dead ça chakalito!", anim = {"anim@mp_player_intcelebrationmale@thumbs_up", "thumbs_up"}},
        {name = "Migraine", anim = {"misscarsteal4@actor", "stumble"}},
        {name = "Amour d\'un bro'", anim = {"anim@mp_player_intcelebrationmale@bro_love", "bro_love"}},
        {name = "Poingnet", anim = {"anim@mp_player_intcelebrationmale@knuckle_crunch", "knuckle_crunch"}},
        {name = "Militaire", anim = {"anim@mp_player_intuppersalute", "idle_a"}, func = 49},
        {name = "GSF", anim = {"amb@code_human_in_car_mp_actions@gang_sign_b@low@ps@base", "idle_a"}, func = 48},
        {name = "Vagos", anim = {"amb@code_human_in_car_mp_actions@v_sign@std@rds@base", "idle_a"}, func = 48},
        {name = "Ballas", anim = {"mp_player_int_uppergang_sign_b", "mp_player_int_gang_sign_b"}, func = 48},
        {name = "Locura", anim = {"mp_player_int_uppergang_sign_a", "mp_player_int_gang_sign_a"}, func = 48},
        {name = "Regarde moi ça!", anim = {"mp_ped_interaction", "handshake_guy_a"}},
        {name = "Regarde moi ça 2", anim = {"mp_ped_interaction", "hugs_guy_a"}},
        {name = "Bon Toutou! Aller!", anim = {"random@street_race", "grid_girl_race_start"}},
        {name = "GG!", anim = {"random@street_race", "_streetracer_accepted"}},
        {name = "BCSO", anim = {"amb@code_human_wander_idles_cop@male@static", "static"}, func = 49},
        {name = "On stop tout !", anim = {"anim@heists@ornate_bank@chat_manager", "fail"}, func = 48},
        },
    ["Poses"] = {
        -- {name = "Prayer", anim = {"rcmepsilonism8", "worship_base"}, func = 1},
        {name = "Auto Stop", anim = {"random@hitch_lift", "idle_f"}, func = 1},
        {name = "Allez, à genoux", anims = {
            enter = { { anim = {"random@arrests@busted", "enter"}, flag = 0 }, { anim = {"random@arrests@busted", "idle_a"}, flag = 1 } },
            exit = { { anim = {"random@arrests@busted", "exit"}, flag = 0 } }
        }
    },
        {name = "Dormir sur place", anim = {"mp_sleep", "sleep_loop"}, func = 49},
        {name = "PLS", anim = {"timetable@tracy@sleep@", "idle_c"}, func = 1},
        {name = "Rouler par terre", anim = {"missfinale_a_ig_2", "trevor_death_reaction_pt"}, func = 2},
        {name = "Blessé au sol", anim = {"combat@damage@rb_writhe", "rb_writhe_loop"}, func = 1},
        {name = "Desespéré", anim = {"rcmnigel1c", "idle_d"}, func = 1},
        {name = "Haleine", anim = {"re@construction", "out_of_breath"}},
        {name = "Faire la statue", anim = "WORLD_HUMAN_HUMAN_STATUE"},
        {name = "Faire le mec", anim = "WORLD_HUMAN_MUSCLE_FLEX"},
        -- {name = "Show it's muscle 2", anim = {"rcmnigel1bnmt_1b", "that_had_to_be_tyler"}},
        -- {name = "Extreme Meditation", anim = {"misscarsteal1leadin", "devon_idle_02"}, func = 1},
        {name = "Zombie", anim = {"special_ped@zombie@monologue_1@monologue_1c", "iamundead_2"}, func = 1},
        {name = "Guarde", anim = {"amb@world_human_stand_guard@male@base", "base"}, func = 49},
        
        {name = "Croisé relou", anim = {"anim@heists@heist_corona@single_team", "single_team_loop_boss"}, func = 1},
        {name = "Bras Croisés", anim = {"random@street_race", "_car_b_lookout"}, func = 1},
        {name = "Holster", anim = {"reaction@intimidation@cop@unarmed", "intro"}, func = 50},
        {name = "Pataugeoire", anim = {"move_m@wading", "walk"}},
        },
    ["Fêtes"] = {
        {name = "Suspense", anim = {"anim@amb@nightclub@dancers@black_madonna_entourage@", "li_dance_facedj_11_v1_male^1"}, f = 1}, -- content
        {name = "Coincé", anim = {"anim@amb@nightclub@dancers@black_madonna_entourage@", "li_dance_facedj_15_v2_male^2"}, f = 1}, -- content
        {name = "Enchainé", anim = {"anim@amb@nightclub@dancers@black_madonna_entourage@", "hi_dance_facedj_09_v2_male^5"}, f = 1}, -- content
        {name = "Hey mec", anim = {"anim@amb@nightclub@dancers@club_ambientpeds@", "mi-hi_amb_club_09_v1_male^1" }, f = 1}, -- content
        {name = "Bouger 01", anim = {"anim@mp_player_intupperuncle_disco", "idle_a"}, func = 1},
        {name = "Bouger 02", anim = {"anim@mp_player_intuppersalsa_roll", "idle_a"}, func = 1},
        {name = "Bouger 03", anim = {"anim@mp_player_intupperraise_the_roof", "idle_a"}, func = 1},
        {name = "Bouger 04", anim = {"anim@mp_player_intupperoh_snap", "idle_a"}, func = 1},
        {name = "Bouger 05", anim = {"anim@mp_player_intupperheart_pumping", "idle_a"}, func = 1},
        {name = "Bouger 06", anim = {"anim@mp_player_intupperfind_the_fish", "idle_a"}, func = 1},
        {name = "Bouger 07", anim = {"anim@mp_player_intuppercats_cradle", "idle_a"}, func = 1},
        {name = "Bouger 08", anim = {"anim@mp_player_intupperbanging_tunes", "idle_a"}, func = 1},
        {name = "Bouger 09", anim = {"anim@mp_player_intupperbanging_tunes_right", "idle_a"}, func = 1},
        {name = "Bouger 10", anim = {"anim@mp_player_intupperbanging_tunes_left", "idle_a"}, func = 1},
        -- {name = "Play music", anim = "WORLD_HUMAN_MUSICIAN"},
        {name = "DJ", anim = {"anim@mp_player_intcelebrationmale@dj", "dj"}},
        {name = "Fausse Guitare", anim = {"anim@mp_player_intcelebrationmale@air_guitar", "air_guitar"}},
        {name = "Jazz", anim = {"anim@mp_player_intcelebrationfemale@jazz_hands", "jazz_hands"}},
        {name = "Rock'n roll", anim = {"anim@mp_player_intcelebrationmale@rock", "rock"}},
        -- {name = "Partying", anim = "WORLD_HUMAN_PARTYING"},
        },
    ["Vulgaire"] = {
        {name = "JPP", anim = {"anim@arena@celeb@flat@solo@no_props@", "giggle_a_player_a"}},
        {name = "Nettoyer le nez", anim = {"anim@mp_player_intcelebrationmale@nose_pick", "nose_pick"}},
        {name = "Bz mon doigt", anim = {"anim@mp_player_intcelebrationmale@finger", "finger"}},
        {name = "Prend mon doigt", anim = {"random@shop_gunstore", "_negative_goodbye"}},
        {name = "Nananere", anim = {"anim@mp_player_intcelebrationmale@thumb_on_ears", "thumb_on_ears"}},
        -- {name = "Vomir", anim = {"missfam5_blackout", "vomit"}},
        {name = "Dans ton UK", anim = {"anim@mp_player_intcelebrationmale@dock", "dock"}},
        {name = "Chuuuuute", anim = {"anim@mp_player_intcelebrationmale@shush", "shush"}},
        {name = "Mouillé", anim = {"anim@mp_player_intcelebrationmale@chicken_taunt", "chicken_taunt"}},
        {name = "Doigt céanim", anims = {
        enter = {{anim = {"anim@mp_player_intselfiethe_bird", "enter"}}, {anim = {"anim@mp_player_intselfiethe_bird", "idle_a"}, flag = 49}},
        exit = {{anim = {"anim@mp_player_intselfiethe_bird", "idle_a"}}, {anim = {"anim@mp_player_intselfiethe_bird", "exit"}}},
        }
        },
        {name = "El famoso doigt", anim = {"mp_player_int_upperfinger", "mp_player_int_finger_01"}, func = 49},
        {name = "Uriner", anim = {"misscarsteal2peeing", "peeing_intro"}},
        {name = "Gratter le UK", anim = {"mp_player_int_upperarse_pick", "mp_player_int_arse_pick"}, func = 49},
        {name = "Gratter les Yekou", anim = {"mp_player_int_uppergrab_crotch", "mp_player_int_grab_crotch"}, func = 49},
        {name = "Pluie d\'argent", anim = {"anim@arena@celeb@flat@solo@props@", "make_it_rain_b_player_b"}},
        {name = "Pluie d\'argent", anim = {"anim@mp_player_intcelebrationmale@raining_cash", "raining_cash"}},
        {name = "AtoûtsF", anim = {"mini@strip_club@backroom@", "stripper_b_backroom_idle_b"}},
        {name = "Coeur", anim = {"mini@hookers_spvanilla", "idle_a"}},
        },
    ["Danses"] = {
        {name = "Dansant", anim = {"misschinese2_crystalmazemcs1_cs", "dance_loop_tao"}},
        {name = "Style", anim = {"missfbi3_sniping", "dance_m_default"}, func = 1},
        {name = "Banal", anim = {"rcmnigel1bnmt_1b", "dance_loop_tyler"}, func = 1},
        
        {name = "Special Dance 1", anim = {"timetable@tracy@ig_5@idle_a", "idle_a"}, func = 1},
        {name = "Twerk", anim = {"mini@strip_club@private_dance@part3", "priv_dance_p3"}},
        {name = "Sexy", anim = {"mp_safehouse", "lap_dance_girl"}},
        {name = "Montrer ses atoûts", anim = {"switch@trevor@mocks_lapdance", "001443_01_trvs_28_idle_stripper"}, func = 49},
        {name = "Special Dance 2", anim = {"timetable@tracy@ig_5@idle_a", "idle_b"}, func = 1},
        {name = "Special Dance 3", anim = {"timetable@tracy@ig_5@idle_b", "idle_e"}, func = 1},
        {name = "Special Dance 4", anim = {"timetable@tracy@ig_5@idle_b", "idle_d"}, func = 1},
        {name = "Pecno", anim = {"special_ped@mountain_dancer@monologue_3@monologue_3a", "mnt_dnc_buttwag"}, func = 1},
        {name = "Basique", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_hi_06_base_laz"}, func = 1},
        {name = "Tourner", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_hi_11_turnaround_laz"}, func = 1},
        {name = "Dance JspskeC2", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_hi_13_crotchgrab_laz"}, func = 1},
        {name = "Voler", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_hi_13_flyingv_laz"}, func = 1},
        {name = "Robot", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_mi_15_robot_laz"}, func = 1},
        {name = "Timide", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_mi_15_shimmy_laz"}, func = 1},
        {name = "Robot Fou", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_hi_15_crazyrobot_laz"}, func = 1},
        {name = "Dance smack", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_hi_17_smackthat_laz"}, func = 1},
        {name = "Araignée", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_hi_17_spiderman_laz"}, func = 1},
        {name = "Hippie", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_li_13_hipswivel_laz"}, func = 1},
        {name = "Stylé", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_li_15_sexygrind_laz"}, func = 1},
        {name = "Dance JspskeC", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_mi_11_pointthrust_laz"}, func = 1},
        {name = "Dance Chelou", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_mi_13_turnaround_laz"}, func = 1},
        {name = "Dance Wtf", anim = {"mini@strip_club@private_dance@idle", "priv_dance_idle"}, func = 1},
        
        {name = "Salsa", anim = {"anim@mp_player_intcelebrationmale@salsa_roll", "salsa_roll"}, func = 1},
        {name = "Dance 1", anim = {"anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v1_male^4"}, func = 1},
        {name = "Dance 2", anim = {"anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v2_female^1"}, func = 1},
        {name = "Dance 3", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_trans_07_mi_to_hi_laz"}, func = 1},
        {name = "Dance 4", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_trans_07_li_to_mi_laz"}, func = 1},
        {name = "Party 5", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_trans_07_hi_to_mi_laz"}, func = 1},
        {name = "Party 6", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_mi_13_enticing_laz"}, func = 1},
        {name = "Party 7", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_mi_11_simplepoint_laz"}, func = 1},
        {name = "Dance 8", anim = {"anim@amb@nightclub@djs@black_madonna@", "dance_b_idle_a_blamadon"}, func = 1},
        {name = "Dance 9", anim = {"anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "high_center"}, func = 1},
        {name = "Dance 10", anim = {"anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "med_center"}, func = 1},
        {name = "Dance 11", anim = {"anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", "high_center_up"}, func = 1},
        {name = "Disco", anim = {"anim@mp_player_intcelebrationmale@uncle_disco", "uncle_disco"}, func = 1},
        },
        ["Armes"] = {
            {name = "Classique", anim = {}, func = function (p) SetWeaponAnimationOverride (p, GetHashKey ("Default")) end},
            {name = "Gangster", anim = {}, func = function (p) SetWeaponAnimationOverride (p, GetHashKey ("Gang1H")) ShowAboveRadarMessage ("~r~Ne fonctionne pas avec toutes les armes.") end},
            {name = "007", anim = {}, func = function (p) SetWeaponAnimationOverride (p, GetHashKey ("Hillbilly")) ShowAboveRadarMessage ("~r~Ne fonctionne pas avec toutes les armes.") end},
            --{name = "JspskeC ?", anim = {}, func = function (p) SetWeaponAnimationOverride (p, GetHashKey ("FirstPersonAiming")) end},
            {name = "Execution", anim = {"oddjobs@suicide", "bystander_pointinto"}, func = 50},
            {name = "Suicide", anim = {"mp_suicide", "pistol"}, func = 2},
            {name = "Regarder l\'arme", anim = {"mp_corona@single_team", "single_team_intro_one"}},
            {name = "Arme tendu", anim = {"random@arrests", "cop_gunaimed_door_open_idle"}},
            --{name = "Combat 1", anim = {"anim@deathmatch_intros@melee@2h", "intro_male_melee_2h_b"}},
            --{name = "Combat 2", anim = {"anim@deathmatch_intros@melee@1h", "intro_male_melee_1h_b"}},
            --{name = "Combat 3", anim = {"anim@deathmatch_intros@melee@1h", "intro_male_melee_1h_c"}},
            --{name = "Combat 4", anim = {"mp_deathmatch_intros@melee@2h", "intro_male_melee_2h_d"}},
            --{name = "Combat 5", anim = {"mp_deathmatch_intros@melee@2h", "intro_male_melee_2h_a_gclub"}},
            --{name = "Combat 6", anim = {"mp_deathmatch_intros@melee@1h", "intro_male_melee_1h_b"}},
            {name = "Combat 1", anim = {"anim@deathmatch_intros@unarmed", "intro_male_unarmed_e"}},
            {name = "Combat 2", anim = {"anim@deathmatch_intros@unarmed", "intro_male_unarmed_d"}},
            {name = "Combat 3", anim = {"anim@deathmatch_intros@unarmed", "intro_male_unarmed_b"}},
        },
        ["Demarche"] = {
            --name  = 'attitudem',
            --name = '👟Démarches',
            
            {name = "Normal homme",animD = {"move_m@generic", "move_m@generic"}},
            {name = "Normal femme",animD = {"move_f@generic", "move_f@generic"}},
            {name = "Confiant homme", animD = {"move_m@confident", "move_m@confident"}},
            {name = "Confiant femme", animD = {"move_f@heels@c", "move_f@heels@c"}},
            {name = "Déprimé homme", animD = {"move_m@depressed@a","move_m@depressed@a"}},
            {name = "Déprimé femme",animD = {"move_f@depressed@a", "move_f@depressed@a"}},
            {name = "Affaires", animD = {"move_m@business@a", "move_m@business@a"}},
            {name = "Déterminer",animD = {"move_m@brave@a","move_m@brave@a"}},
            {name = "Non chalant",animD = {"move_m@casual@a","move_m@casual@a"}},
            {name = "Audacieux", animD = {"move_m@fat@a", "move_m@fat@a"}},
            {name = "Hipster",animD = {"move_m@hipster@a","move_m@hipster@a"}},
            {name = "Blesser",animD = {"move_m@injured", "move_m@injured"}},
            {name = "Pressé",animD = {"move_m@hurry@a", "move_m@hurry@a"}},
            {name = "Sans abri",animD = {"move_m@hobo@a","move_m@hobo@a"}},
            {name = "Désolé",animD = {"move_m@sad@a", "move_m@sad@a"}},
            {name = "Muscler",animD = {"move_m@muscle@a", "move_m@muscle@a"}},
            {name = "Choqué", animD = {"move_m@shocked@a","move_m@shocked@a"}},
            {name = "Bonhomme",animD = {"move_m@shadyped@a","move_m@shadyped@a"}},
            {name = "HUM", animD = {"move_m@buzzed", "move_m@buzzed"}},
            {name = "Pressé 2", animD = {"move_m@hurry_butch@a", "move_m@hurry_butch@a"}},
            {name = "Argent",  animD = {"move_m@money", "move_m@money"}},
            {name = "Rapide", animD = {"move_m@quick", "move_m@quick"}},
            {name = "Tord du cul!",animD = {"move_f@maneater", "move_f@maneater"}},
            {name = "Grossier", animD = {"move_f@sassy", "move_f@sassy"}},
            {name = "Arrogant", animD = {"move_f@arrogant@a",  "move_f@arrogant@a"}},
            {name = "Gangster", animD = {"move_m@gangster@generic","move_m@gangster@generic"}},
            {name = "Alcoolisé", animD = {"move_m@drunk@verydrunk", "move_m@drunk@verydrunk"}},
            --{name = "Ramper Blesser", animD = {"move_injured_ground", "front_loop"}},
            --{name = "Ramper",animD = {"move_crawl", "onfront_fwd"}},
    
        },
    

}